"""initial schema

Revision ID: ba8784afef48
Revises: 
Create Date: 2025-10-26 10:13:58.227227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8784afef48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_encrypted', sa.Text(), nullable=False),
    sa.Column('phone_number_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_hash')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_created', ['created_at'], unique=False)
        batch_op.create_index('idx_user_phone_hash', ['phone_number_hash'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=True),
    sa.Column('ai_response_encrypted', sa.Text(), nullable=True),
    sa.Column('parsed_tasks', sa.Text(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('idx_message_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_message_user_type', ['user_id', 'message_type'], unique=False)
        batch_op.create_index('idx_message_whatsapp_id', ['whatsapp_message_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('idx_task_created', ['created_at'], unique=False)
        batch_op.create_index('idx_task_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_task_status', ['status'], unique=False)
        batch_op.create_index('idx_task_status_due', ['status', 'due_date'], unique=False)
        batch_op.create_index('idx_task_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_task_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('idx_task_user_status')
        batch_op.drop_index('idx_task_user_created')
        batch_op.drop_index('idx_task_status_due')
        batch_op.drop_index('idx_task_status')
        batch_op.drop_index('idx_task_due_date')
        batch_op.drop_index('idx_task_created')

    op.drop_table('task')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_whatsapp_id')
        batch_op.drop_index('idx_message_user_type')
        batch_op.drop_index('idx_message_user_created')

    op.drop_table('message')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_phone_hash')
        batch_op.drop_index('idx_user_created')

    op.drop_table('user')
    # ### end Alembic commands ###
